# Generated by Django 3.2.5 on 2022-01-14 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default=1, max_length=14)),
                ('date_of_birth', models.DateField(default='1975-01-01')),
                ('door_no', models.CharField(default='A-BCD, On Earth', max_length=100)),
                ('zip_code', models.CharField(default='123456', max_length=8)),
                ('city_name', models.CharField(default='Vijayawada', max_length=50)),
                ('state_name', models.CharField(default='Andhra Pradesh', max_length=50)),
                ('country_name', models.CharField(default='India', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staffs/')),
                ('current_medical_issue', models.TextField(max_length=50)),
                ('blood_group', models.CharField(choices=[('', 'Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=1, max_length=18)),
                ('branch', models.CharField(choices=[('', 'Branch Name'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Aerospace/aeronautical Engineering', 'Aerospace/aeronautical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Bio Technology', 'Bio Technology'), ('Mechanical Engineering', 'Mechanical Engineering')], default=1, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
