# Generated by Django 3.2.5 on 2022-01-14 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('block_name', models.CharField(max_length=50, unique=True)),
                ('block_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['block_name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('floor_name', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.block')),
            ],
            options={
                'ordering': ['floor_name'],
                'unique_together': {('floor_name', 'block')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mode', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], default=1, max_length=4)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Class Room', 'Class Room'), ('Staff Room', 'Staff Room'), ('Waiting Hall', 'Waiting Hall'), ('Lab', 'Lab'), ('Meeting Hall', 'Meeting Hall')], default=1, max_length=15)),
                ('capacity', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.floor')),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
    ]
