# Generated by Django 3.2.5 on 2022-01-14 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialization', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_short_info', models.TextField(default='Start your path to a career in project management. No degree or experience is required.', max_length=500)),
                ('course_wywl', models.TextField(default='WHAT YOU WILL LEARN', max_length=500)),
                ('course_sywg', models.TextField(default='SKILLS YOU WILL GAIN', max_length=500)),
                ('course_desc', models.TextField(default='Description of the Course', max_length=500)),
                ('branch', models.CharField(choices=[('', 'Branch Name'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Aerospace/aeronautical Engineering', 'Aerospace/aeronautical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Bio Technology', 'Bio Technology'), ('Mechanical Engineering', 'Mechanical Engineering')], default=1, max_length=50)),
                ('course_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.semester')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialization.specializationsmc')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecomponent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemc')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.FileField(upload_to='TaskAnswerFiles/')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecomponent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemc')),
                ('sub_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesubcomponent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursetask',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.taskanswer'),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecomponent'),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemc'),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='sub_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesubcomponent'),
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_files', models.FileField(blank=True, null=True, upload_to='Course_Files/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemc')),
            ],
        ),
        migrations.AddField(
            model_name='coursecomponent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemc'),
        ),
    ]
