# Generated by Django 3.2.5 on 2022-01-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpagevisits',
            name='userIPAddr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
